spring:
  cloud:
    gateway:
      # 设置路由id 路由到微服务的url 以及断言
      routes:
      - id: order_rout #路由ID 全局唯一
        uri: lb://Gateway-sample #目标微服务 地址喝端口
        predicates:
        # 测试：http://localhost:8888/order/findOrderByUserId/1
        - Path=/test/**